// <auto-generated />
using System;
using CRUD_CodeFirstCoursesDataBase_WEBAPI_day3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUD_CodeFirstCoursesDataBase_WEBAPI_day3.Migrations
{
    [DbContext(typeof(courseContext))]
    [Migration("20241106201344_creatingDataBase")]
    partial class creatingDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRUD_CodeFirstCoursesDataBase_WEBAPI_day3.Models.courses", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Crs_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("crs_desc")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ID");

                    b.ToTable("courses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Crs_name = "Introduction to Programming",
                            Duration = 30,
                            crs_desc = "Basic programming concepts"
                        },
                        new
                        {
                            ID = 2,
                            Crs_name = "Data Structures",
                            Duration = 40,
                            crs_desc = "Learn various data structures"
                        },
                        new
                        {
                            ID = 3,
                            Crs_name = "Web Development",
                            Duration = 45,
                            crs_desc = "Building web applications"
                        },
                        new
                        {
                            ID = 4,
                            Crs_name = "Database Management",
                            Duration = 35,
                            crs_desc = "Fundamentals of database systems"
                        },
                        new
                        {
                            ID = 5,
                            Crs_name = "Machine Learning",
                            Duration = 50,
                            crs_desc = "Introduction to machine learning concepts"
                        },
                        new
                        {
                            ID = 6,
                            Crs_name = "Embedded Systems",
                            Duration = 25,
                            crs_desc = "Basics of embedded system design"
                        },
                        new
                        {
                            ID = 7,
                            Crs_name = "Cloud Computing",
                            Duration = 40,
                            crs_desc = "Introduction to cloud services"
                        },
                        new
                        {
                            ID = 8,
                            Crs_name = "Cybersecurity Basics",
                            Duration = 30,
                            crs_desc = "Foundations of cybersecurity"
                        },
                        new
                        {
                            ID = 9,
                            Crs_name = "Artificial Intelligence",
                            Duration = 55,
                            crs_desc = "AI concepts and applications"
                        },
                        new
                        {
                            ID = 10,
                            Crs_name = "Networking Essentials",
                            Duration = 20,
                            crs_desc = "Fundamentals of networking"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
